name: Testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PYTHON_VERSION: '3.10'
  PACKAGE_NAME: code-preprocessor
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-images:
    name: Build Docker Images
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      test_image_tag: ${{ steps.meta-test.outputs.tags }}
      prod_image_tag: ${{ steps.meta-prod.outputs.tags }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for test image
        id: meta-test
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-test

      - name: Build and push test image
        uses: docker/build-push-action@v5
        with:
          context: .
          target: test
          push: true
          tags: ${{ steps.meta-test.outputs.tags }}
          labels: ${{ steps.meta-test.outputs.labels }}
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-test:latest
          cache-to: type=inline

      - name: Extract metadata for production image
        id: meta-prod
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push production image
        uses: docker/build-push-action@v5
        with:
          context: .
          target: production
          push: true
          tags: ${{ steps.meta-prod.outputs.tags }}
          labels: ${{ steps.meta-prod.outputs.labels }}
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          cache-to: type=inline

  format:
    name: Code Formatting
    needs: [build-images]
    runs-on: ubuntu-latest
    container:
      image: ${{ needs.build-images.outputs.test_image_tag }}
    steps:
      - name: Check formatting
        run: |
          black --check .
          isort --check-only --diff .

  lint:
    name: Linting
    needs: [build-images]
    runs-on: ubuntu-latest
    container:
      image: ${{ needs.build-images.outputs.test_image_tag }}
    steps:
      - name: Run linters
        run: |
          flake8 ${{ env.PACKAGE_NAME }}/
          pylint ${{ env.PACKAGE_NAME }}/

  type-check:
    name: Type Checking
    needs: [build-images]
    runs-on: ubuntu-latest
    container:
      image: ${{ needs.build-images.outputs.test_image_tag }}
    steps:
      - name: Run mypy
        run: |
          mypy ${{ env.PACKAGE_NAME }}/

  test:
    name: Run Tests
    needs: [build-images]
    runs-on: ubuntu-latest
    container:
      image: ${{ needs.build-images.outputs.test_image_tag }}
    steps:
      - name: Run tests
        run: |
          pytest --cov --cov-report=xml
      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          # fail_ci_if_error: true

  build:
    name: Build Package
    needs: [test]
    runs-on: ubuntu-latest
    container:
      image: ${{ needs.build-images.outputs.test_image_tag }}
    steps:
      - name: Build and check package
        run: |
          python -m build
          twine check dist/*

  compatibility:
    name: Python Compatibility
    needs: [test]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: ['3.10', '3.11']
    container:
      image: python:${{ matrix.python-version }}-slim
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"
      - name: Run tests
        run: |
          pytest
