name: Testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  format:
    name: Code Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"
        continue-on-error: false
      - name: Check black formatting
        run: |
          black --check .
        continue-on-error: false
      - name: Check import sorting
        run: |
          isort --check-only --diff .
        continue-on-error: false

  lint:
    name: Linting
    needs: [format]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"
        continue-on-error: false
      - name: Run flake8
        run: |
          flake8 code_preprocessor/
        continue-on-error: false
      - name: Run pylint
        run: |
          pylint code_preprocessor/
        continue-on-error: false

  type-check:
    name: Type Checking
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
        continue-on-error: false
      - name: Run mypy
        run: |
          mypy code_preprocessor/
        continue-on-error: false

  test:
    name: Run Tests (CPU)
    needs: [type-check]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
        continue-on-error: false
      - name: Run tests
        run: |
          pytest --cov --cov-report=xml
        continue-on-error: false
      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          fail_ci_if_error: true

  build:
    name: Build Package
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine
        continue-on-error: false
      - name: Build package
        run: |
          python -m build
        continue-on-error: false
      - name: Check wheel and sdist
        run: |
          twine check dist/*
        continue-on-error: false

  compatibility:
    name: Python Compatibility
    needs: [test]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: ['3.10', '3.11']
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"
        continue-on-error: false
      - name: Run tests
        run: |
          pytest
        continue-on-error: false
