name: Testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Default permissions for all jobs unless overridden
permissions: read-all

env:
  PYTHON_VERSION: '3.10'
  PACKAGE_NAME: code-preprocessor
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-image:
    name: Build Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write  # Needed for pushing to ghcr.io
    outputs:
      image_tag: ${{ steps.meta.outputs.tags }}
    steps:
      - uses: actions/checkout@v4.1.1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@0d103c3126aa41d772a8362f6aa67afac040f80c # v3.0.0

      - name: Log in to the Container registry
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@96383f45573cb7f253c731d3b3ab81c87ef81934 # v5.0.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Store short sha
        id: short_sha
        run: |
          echo "short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build and push image
        uses: docker/build-push-action@4a13e500e55cf31b7a5d59a38ab2040ab0f42f56 # v5.1.0
        with:
          context: .
          push: true
          tags: |
            ${{ steps.meta.outputs.tags }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:sha-${{ github.sha }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          cache-to: type=inline

  format:
    name: Code Formatting
    needs: [build-image]
    runs-on: ubuntu-latest
    permissions:
      contents: read  # Only needs to read files
    container:
      image: ${{ needs.build-image.outputs.image_tag }}
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Check formatting
        run: |
          black --check .
          isort --check-only --diff .

  lint:
    name: Linting
    needs: [build-image]
    runs-on: ubuntu-latest
    permissions:
      contents: read  # Only needs to read files
    container:
      image: ${{ needs.build-image.outputs.image_tag }}
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Run linters
        run: |
          flake8 ./code_preprocessor
          pylint ./code_preprocessor

  type-check:
    name: Type Checking
    needs: [build-image]
    runs-on: ubuntu-latest
    permissions:
      contents: read  # Only needs to read files
    container:
      image: ${{ needs.build-image.outputs.image_tag }}
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Run mypy
        run: |
          mypy . --ignore-missing-imports

  test:
    name: Run Tests
    needs: [build-image]
    runs-on: ubuntu-latest
    permissions:
      contents: read  # Needed to read files
      checks: write   # Needed for test reporting
    container:
      image: ${{ needs.build-image.outputs.image_tag }}
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Run tests
        run: |
          pytest --cov --cov-report=xml
      - name: Upload coverage
        uses: codecov/codecov-action@ab904c41d6ece82784817410c45d8b8c02684457 # v3.1.4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          fail_ci_if_error: true
          verbose: true

  build:
    name: Build Package
    needs: [test]
    runs-on: ubuntu-latest
    permissions:
      contents: read  # Only needs to read files
    container:
      image: ${{ needs.build-image.outputs.image_tag }}
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine
      - name: Build and check package
        run: |
          python -m build
          twine check dist/*

  compatibility:
    name: Python Compatibility
    needs: [test]
    runs-on: ubuntu-latest
    permissions:
      contents: read  # Only needs to read files
    strategy:
      fail-fast: true
      matrix:
        python-version: ['3.10', '3.11']
    container:
      image: python:${{ matrix.python-version }}-slim
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"
      - name: Run tests
        run: |
          pytest

  update-changelog:
    name: Update Changelog
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: [compatibility, build]
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Needed to commit changes
      pull-requests: write  # Needed to create pull requests
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0  # Fetch all history for proper versioning
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check for changes
        id: check_changes
        run: |
          # Get the latest tag or default to empty
          latest_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "")

          if [ -z "$latest_tag" ]; then
            # No tags exist, this is first version
            echo "has_changes=true" >> $GITHUB_OUTPUT
            echo "new_version=v0.1.0" >> $GITHUB_OUTPUT
          else
            # Check if there are any changes in tracked files since last tag
            if git diff --quiet "$latest_tag" HEAD -- ':(exclude)CHANGELOG.md'; then
              echo "has_changes=false" >> $GITHUB_OUTPUT
            else
              echo "has_changes=true" >> $GITHUB_OUTPUT
              # Increment patch version
              IFS='.' read -r major minor patch <<< "${latest_tag#v}"
              echo "new_version=v$major.$minor.$((patch + 1))" >> $GITHUB_OUTPUT
            fi
          fi
          echo "date=$(date +%Y-%m-%d)" >> $GITHUB_OUTPUT

      - name: Update CHANGELOG.md
        if: steps.check_changes.outputs.has_changes == 'true'
        run: |
          # Read current changelog
          content=$(cat CHANGELOG.md)

          # Create new version section
          new_version_section="## [${{ steps.check_changes.outputs.new_version }}] - ${{ steps.check_changes.outputs.date }}"

          # Replace [Unreleased] with new version and add new [Unreleased] section
          echo "$content" | sed "0,/## \[Unreleased\]/s/## \[Unreleased\]/## [Unreleased]\n\n### Added\n\n### Changed\n\n### Fixed\n\n$new_version_section/" > CHANGELOG.md

      - name: Create Pull Request
        if: steps.check_changes.outputs.has_changes == 'true'
        uses: peter-evans/create-pull-request@153407881ec5c347639a548ade7d8ad1d6740e38 # v5.0.2
        with:
          commit-message: "chore: update changelog for ${{ steps.check_changes.outputs.new_version }}"
          title: "chore: update changelog for ${{ steps.check_changes.outputs.new_version }}"
          body: |
            Automated changelog update for version ${{ steps.check_changes.outputs.new_version }}

            This PR:
            1. Moves current unreleased changes to version ${{ steps.check_changes.outputs.new_version }}
            2. Creates a new empty unreleased section
          branch: changelog-update
          base: main
          delete-branch: true
